name: MistySamplerApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_app:
    name: App build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Run build
        run: |
          npm i
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Install node modules
        run: |
          npm i
          npm run test
